### ISSUE TITLE
Invalid Bitcoin URI (qr code)

### ISSUE THREAD

**Issue by theshanergy** [XertroV/nodeup-xk-io#1]
Using the latest 'Bitcoin Wallet' on Android, I receive an 'Invalid Bitcoin URI' error upon scanning the provided qr code.

**Comment by XertroV** [comment]
Hmm, a friend of mine reported trouble scanning from one wallet and not another. Could you please see if you can replicate it, and if so, copy paste the URI here (you should be able to right-click copy link, and they're generated from the same source). Also try mycelium, if you have it. That's what I've been using to test and it works well.

**Comment by XertroV** [comment]
Okay, I've replicated the issue (which was trivial) and I think it was the spaces in the URI.

I can now scan from Bitcoin Wallet, so it's all good from where I stand.

**Comment by theshanergy** [comment]
Confirmed - works on my end!

**Comment by XertroV** [comment]
Excellent! Thanks for the confirmation.
